version: '3.1'
services:
    management_database:
        image: mysql
        container_name: management_db
        environment:
            MYSQL_DATABASE: management_db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
            
    shipping_database:
        image: mysql
        container_name: shipping_db
        environment:
            MYSQL_DATABASE: shipping_db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3307:3306"
            
    manage-order-service:
        image: manage-order-service:v1
        restart: on-failure
        container_name: manage-order-service
        ports:
            - "8082:8082"
        environment:
            - "SPRING_PROFILES_ACTIVE=prod"
            - "HOST_DB=management_database"
            - "PORT_DB=3306"
            - "DB_NAME=management_db"
            - "USER_NAME_DB=root"
            - "PASSWORD_DB=root"
        depends_on:
            - management_database
    
    shipping-service:
        image: shipping-service:v1
        restart: on-failure
        container_name: shipping-service
        ports:
            - "8083:8083"
        environment:
            - "SPRING_PROFILES_ACTIVE=prod"
            - "HOST_DB=shipping_database"
            - "PORT_DB=3306"
            - "DB_NAME=shipping_db"
            - "USER_NAME_DB=root"
            - "PASSWORD_DB=root"
        depends_on:
            - shipping_database
