version: '3.1'
services:
    manage-order-service:
        image: manage-order-service:v1
        container_name: manage-order-service
        ports:
            - "8082:8082"
    shipping-service:
        image: shipping-service:v1
        container_name: shipping-service
        ports:
            - "8083:8083"